/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cenxui' at '12/21/16 4:40 PM' with Gradle 2.14.1
 *
 * @author cenxui, @date 12/21/16 4:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
